### ISSUE TITLE
Grand Tree - Black Demon un-killable [Quest can be completed without]

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#928]
When trying to kill the black demon(175) doing Grand Tree will never die, you will still be able to hit him for your normal damage but he will never die.
Fleeing the combat and continue the quest as he was defeated do work.

**Comment by Christofosho** [comment]
Does it work now that the previous bug was fixed with 1-hit npcs?

**Comment by Christofosho** [comment]
@LionRsc do you need this quest reset on your character?

**Comment by ZephORSC** [comment]
This bug is still in the live version of the game as of 11/11

**Comment by Kenix3** [comment]
This issue is closed but the bug still exists
Getting the black demon to no health triggers the flag to advance
He just doesnt die
- Zeph on Discord

**Comment by lmsv-mx123** [comment]
Tested local and now appears to die.
